### ISSUE TITLE
Mac osx build errors

### ISSUE THREAD

**Issue by 0x1337coding** [CuteCubed/Arionum-Electron#6]
On latest Mac Osx 

(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.

also on electron 

Uncaught Exception:
TypeError: Cannot read property 'setHighlightMode' of undefined
    at BrowserWindow.<anonymous> (/Users/user/wallets/Arionum-Electron/main.js:156:10)
    at BrowserWindow.emit (events.js:187:15)

Also as soon as the error message appears the application refuses to close..

**Comment by pxgamer** [comment]
The first issue will be resolved by #3.

I'm sure @CuteCubed will be able to fix the 2nd issue. It's from this:
https://github.com/CuteCubed/Arionum-Electron/blob/eb5319b089bcd2bf65af241dd2404a20574aa415/main.js#L155-L158

The `tray` variable is undefined, I don't seem to get the error on Windows, so it might be a MacOS issue?

**Comment by 0x1337coding** [comment]
yes most probably. i have not tested the wallet on windows

**Comment by pxgamer** [comment]
It looks like c6a99b18857a445717e87e1154baee9d953c20c1 should have fixed this issue according to @CuteCubed, but it wasn't mentioned. :thinking: Perhaps this issue can be closed.

Just testing it on Mac. :+1:
